version: "3.8"
services:
  postgresql:
    image: postgresql
    build: postgresql/
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    networks:
      - services-network
  mongodb:
    image: "mongo"
    container_name: "mongodb_orders"   
    ports:
      - "27017:27017"
    networks: 
      - services-network
  orders:
    image: orders
    build: orders/
    container_name: orders_service
    depends_on:
      - "mongodb"
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=mongodb
      - FLIGHT_SERVICE_BASE_URL=http://flight:8080
      - HOTEL_SERVICE_BASE_URL=http://hotel:8080
    networks: 
      - services-network
  flight:
    image: flight
    build: flight/
    container_name: flight_service
    depends_on:
      - "postgresql"
      - "payments"   
    environment:
      - DATABASE_HOST=postgresql
      - DATABASE_PORT=5432
      - DATABASE_NAME=flightdb
      - DATABASE_USERNAME=flight_service
      - DATABASE_PASSWORD=flight_service_123
      - PAYMENTS_BASE_URL=http://payments:8080
    networks: 
      - services-network
  hotel:
    image: hotel
    build: hotel/
    container_name: hotel_service
    depends_on:
      - "postgresql"
      - "payments"    
    environment:
      - DATABASE_HOST=postgresql
      - DATABASE_PORT=5432
      - DATABASE_NAME=hoteldb
      - DATABASE_USERNAME=hotel_service
      - DATABASE_PASSWORD=hotel_service_123
      - PAYMENTS_BASE_URL=http://payments:8080
    networks: 
      - services-network
  payments:
    image: payments
    build: payments/
    container_name: payments_service
    depends_on:
      - "postgresql"    
    environment:
      - DATABASE_HOST=postgresql
      - DATABASE_PORT=5432
      - DATABASE_NAME=paymentsdb
      - DATABASE_USERNAME=payments_service
      - DATABASE_PASSWORD=payments_service_123        
    networks: 
      - services-network
networks:
  services-network:
    driver: "bridge"
