version: "3.8"
services:
  postgresql:
    image: postgresql
    build: postgresql/
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    networks:
      - services-network
  #rabbitmq:
  #  image: rabbitmq
  #  build: rabbitmq/
  #  container_name: rabbitmq
  #  ports:
  #    - "5672:5672"
  #    - "15672:15672"
  #  networks:
  #    - services-network
networks:
  services-network:
    driver: "bridge"
