version: "3.8"
services:
  creditdb:
    image: creditdb
    build: postgresql/
    container_name: creditdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=creditdb
    networks:
      - services-network
networks:
  services-network:
    driver: "bridge"
