server:
  port: ${SERVER_PORT:8080}
spring:
  data:
    mongodb:
      database: ${DATABASE_NAME:ordersdb}
      host: ${DATABASE_HOST:localhost}
      port: ${DATABASE_PORT:27017}

collections:
  orders-collection: ${ORDERS_COLLECTION:orders}