server:
  port: ${SERVER_PORT:8080}
spring:
  data:
    mongodb:
      database: ${DATABASE_NAME:ordersdb}
      host: ${DATABASE_HOST:localhost}
      port: ${DATABASE_PORT:27017}
camel:
  component:
    servlet:
      mapping:
        contextPath: /*
#  service:
#    lra:
#      enabled: true
#  lra:
#    coordinator-url: ${LRA_COORDINATOR_BASE_URL:http://localhost:9000}
#    local-participant-url: ${LRA_LOCAL_PARTICIPANT_BASE_URL:http://localhost:8081}
web:
  client:
    flight:
      base-url: http://${FLIGHT_SERVICE_HOST:localhost}:${FLIGHT_SERVICE_PORT:8081}
    hotel:
      base-url: http://${HOTEL_SERVICE_HOST:localhost}:${HOTEL_SERVICE_PORT:8082}
collections:
  orders-collection: ${ORDERS_COLLECTION:orders}