CREATE USER credit_service;
ALTER USER credit_service WITH PASSWORD 'credit_service_123';
GRANT ALL PRIVILEGES ON DATABASE creditdb TO credit_service;

CREATE TABLE ACCOUNT (
    ID UUID NOT NULL,
    USED NUMERIC NOT NULL,
    MAX_LIMIT NUMERIC NOT NULL,
    CONSTRAINT CREDIT_PK PRIMARY KEY (ID)
);

CREATE TABLE OPERATION (
    ID UUID NOT NULL,
    OPERATION_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT OPERATION_PK PRIMARY KEY (ID)
);


INSERT INTO ACCOUNT VALUES ('2aa2ae05-3761-4d4a-926b-6a27031192e5', 0, 100)