server:
  port: ${SERVER_PORT:8082}
spring:
  r2dbc:
    url: r2dbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:hoteldb}
    username: ${DATABASE_USERNAME:hotel_service}
    password: ${DATABASE_PASSWORD:hotel_service_123}
  rabbitmq:
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
web:
  client:
    payments:
      base-url: ${PAYMENTS_BASE_URL:http://localhost:8083}
queue:
  booking-request: ${BOOKING_REQUEST_QUEUE_NAME:booking_request}
  booking-response: ${BOOKING_RESPONSE_QUEUE_NAME:booking_response}

