server:
  port: ${SERVER_PORT:8082}
spring:
  r2dbc:
    url: r2dbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:hoteldb}
    username: ${DATABASE_USERNAME:hotel_service}
    password: ${DATABASE_PASSWORD:hotel_service_123}

